# Generated by Django 2.1 on 2018-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0007_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Candidate'), (2, 'Processed'), (3, 'Converted'), (4, 'Rejected')], default=1, null=True),
        ),
    ]
