# Generated by Django 2.1 on 2018-10-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0008_auto_20181027_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('Candidate', 'Candidate'), ('Processed', 'Processed'), ('Converted', 'Converted'), ('Rejecte', 'Rejected')], default='Candidate', max_length=10, null=True),
        ),
    ]
