# Generated by Django 2.1 on 2018-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0009_auto_20181027_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='corporate_investor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('Candidate', 'Candidate'), ('Processed', 'Processed'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Candidate', max_length=10, null=True),
        ),
    ]
