# Generated by Django 2.1 on 2018-12-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0011_auto_20181230_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, default='example@google.com', max_length=254, null=True),
        ),
    ]
