# Generated by Django 2.1 on 2019-01-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0015_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='count_lead',
            new_name='lead_count',
        ),
    ]
