# Generated by Django 2.1 on 2019-01-10 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0016_auto_20190106_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_message', to='drfreact_api.Message'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
