# Generated by Django 2.1 on 2019-01-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0018_auto_20190110_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='payments',
        ),
    ]
