# Generated by Django 2.1 on 2019-01-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0020_message_is_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='lead_count',
        ),
    ]
