# Generated by Django 2.1 on 2019-01-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0022_message_last_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_call',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
