# Generated by Django 2.1 on 2019-01-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0023_auto_20190125_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
