# Generated by Django 2.1 on 2019-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0024_auto_20190125_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='correspondence',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='documents',
            field=models.FileField(blank=True, default='', upload_to='files'),
        ),
    ]
