# Generated by Django 2.1.7 on 2019-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfreact_api', '0025_auto_20190130_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='documents',
            field=models.FileField(blank=True, default='', upload_to='static/files'),
        ),
    ]
